const convertLanguageNameToISO = (language) => {
    return a[language];
}
const a = {
    "Afar":"aa",
    "Abkhazian":"ab",
    "Avestan":"ae",
    "Afrikaans":"af",
    "Akan":"ak",
    "Amharic":"am",
    "Aragonese":"an",
    "Arabic":"ar",
    "Assamese":"as",
    "Avaric":"av",
    "Aymara":"ay",
    "Azerbaijani":"az",
    "Bashkir":"ba",
    "Belarusian":"be",
    "Bulgarian":"bg",
    "Bihari":"bh",
    "Bislama":"bi",
    "Bambara":"bm",
    "Bengali":"bn",
    "Tibetan":"bo",
    "Breton":"br",
    "Bosnian":"bs",
    "Catalan":"ca",
    "Valencian":"ca",
    "Chechen":"ce",
    "Chamorro":"ch",
    "Corsican":"co",
    "Cree":"cr",
    "Czech":"cs",
    "Slavic":"cu",
    "Chuvash":"cv",
    "Welsh":"cy",
    "Danish":"da",
    "German":"de",
    "Divehi":"dv",
    "Dhivehi":"dv",
    "Maldivian":"dv",
    "Dzongkha":"dz",
    "Ewe":"ee",
    "Greek":"el",
    "English":"en",
    "Esperanto":"eo",
    "Spanish":"es",
    "Castilian":"es",
    "Estonian":"et",
    "Basque":"eu",
    "Persian":"fa",
    "Fulah":"ff",
    "Finnish":"fi",
    "Fijian":"fj",
    "Faroese":"fo",
    "French":"fr",
    "Western Frisian":"fy",
    "Irish":"ga",
    "Gaelic":"gd",
    "Scomttish Gaelic":"gd",
    "Galician":"gl",
    "Guarani":"gn",
    "Gujarati":"gu",
    "Manx":"gv",
    "Hausa":"ha",
    "Hebrew":"he",
    "Hindi":"hi",
    "Hiri Motu":"ho",
    "Croatian":"hr",
    "Haitian":"ht",
    "Haitian Creole":"ht",
    "Hungarian":"hu",
    "Armenian":"hy",
    "Herero":"hz",
    "Interlingua":"ia",
    "Indonesian":"id",
    "Interlingue":"ie",
    "Occidental":"ie",
    "Igbo":"ig",
    "Sichuan Yi":"ii",
    "Nuosu":"ii",
    "Inupiaq":"ik",
    "Ido":"io",
    "Icelandic":"is",
    "Italian":"it",
    "Inuktitut":"iu",
    "Japanese":"ja",
    "Javanese":"jv",
    "Georgian":"ka",
    "Kongo":"kg",
    "Kikuyu":"ki",
    "Gikuyu":"ki",
    "Kuanyama":"kj",
    "Kwanyama":"kj",
    "Kazakh":"kk",
    "Kalaallisut":"kl",
    "Greenlandic":"kl",
    "Central Khmer":"km",
    "Kannada":"kn",
    "Korean":"ko",
    "Kanuri":"kr",
    "Kashmiri":"ks",
    "Kurdish":"ku",
    "Komi":"kv",
    "Cornish":"kw",
    "Kirghiz":"ky",
    "Kyrgyz":"ky",
    "Latin":"la",
    "Luxembourgish":"lb",
    "Letzeburgesch":"lb",
    "Ganda":"lg",
    "Limburgan":"li",
    "Limburger":"li",
    "Limburgish":"li",
    "Lingala":"ln",
    "Lao":"lo",
    "Lithuanian":"lt",
    "Luba-Katanga":"lu",
    "Latvian":"lv",
    "Malagasy":"mg",
    "Marshallese":"mh",
    "Maori":"mi",
    "Macedonian":"mk",
    "Malayalam":"ml",
    "Mongolian":"mn",
    "Marathi":"mr",
    "Malay":"ms",
    "Maltese":"mt",
    "Burmese":"my",
    "Nauru":"na",
    "Bokmål, Norwegian":"nb",
    "Norwegian Bokmål":"nb",
    "Ndebele, North":"nd",
    "North Ndebele":"nd",
    "Nepali":"ne",
    "Ndonga":"ng",
    "Dutch; Flemish":"nl",
    "Norwegian Nynorsk":"nn",
    "Nynorsk, Norwegian":"nn",
    "Norwegian":"no",
    "Ndebele, South":"nr",
    "South Ndebele":"nr",
    "Navajo":"nv",
    "Navaho":"nv",
    "Chichewa":"ny",
    "Chewa":"ny",
    "Nyanja":"ny",
    "Occitan":"oc",
    "Ojibwa":"oj",
    "Oromo":"om",
    "Oriya":"or",
    "Ossetian":"os",
    "Ossetic":"os",
    "Panjabi":"pa",
    "Punjabi":"pa",
    "Pali":"pi",
    "Polish":"pl",
    "Pushto":"ps",
    "Pashto":"ps",
    "Portuguese":"pt",
    "Quechua":"qu",
    "Romansh":"rm",
    "Rundi":"rn",
    "Romanian":"ro",
    "Moldavian":"ro",
    "Moldovan":"ro",
    "Russian":"ru",
    "Kinyarwanda":"rw",
    "Sanskrit":"sa",
    "Sardinian":"sc",
    "Sindhi":"sd",
    "Northern Sami":"se",
    "Sango":"sg",
    "Sinhala":"si",
    "Sinhalese":"si",
    "Slovak":"sk",
    "Slovenian":"sl",
    "Samoan":"sm",
    "Shona":"sn",
    "Somali":"so",
    "Albanian":"sq",
    "Serbian":"sr",
    "Swati":"ss",
    "Sotho, Southern":"st",
    "Sundanese":"su",
    "Swedish":"sv",
    "Swahili":"sw",
    "Tamil":"ta",
    "Telugu":"te",
    "Tajik":"tg",
    "Thai":"th",
    "Tigrinya":"ti",
    "Turkmen":"tk",
    "Tagalog":"tl",
    "Tswana":"tn",
    "Tonga":"to",
    "Turkish":"tr",
    "Tsonga":"ts",
    "Tatar":"tt",
    "Twi":"tw",
    "Tahitian":"ty",
    "Uighur":"ug",
    "Uyghur":"ug",
    "Ukrainian":"uk",
    "Urdu":"ur",
    "Uzbek":"uz",
    "Venda":"ve",
    "Vietnamese":"vi",
    "Volapük":"vo",
    "Walloon":"wa",
    "Wolof":"wo",
    "Xhosa":"xh",
    "Yiddish":"yi",
    "Yoruba":"yo",
    "Zhuang":"za",
    "Chuang":"za",
    "Chinese":"zh",
    "Zulu":"zu",
}

module.exports = convertLanguageNameToISO;
